MODEL_NAME = 'igcn_embed'
MODEL_VER = '1'
DATASET = 'laptop'
OPTIMIZER = 'adam'
INITIALIZER = 'xavier_uniform_'
LEARNING_RATE = 3e-4
L2REG = 5e-5
NUM_EPOCH = 50
BATCH_SIZE = 32
LOG_STEP = 5
EMBEDDING_DIM = 100
HIDDEN_DIM = 300
MAX_SEQ_LEN = 80
POLARITY_DIM = 3
SEED = 0
VALSET_RATIO = 0
DROPOUT = 0.5
MOMENTUM = 0.95
EMBEDDINGS = 'd'

# Gating options
GATING = 'GTU'

# Position Dim
POSITION_DIM = 100

# Gated CNN
NUM_LAYERS = 1
IN_CHANNELS = 100
OUT_CHANNELS = 1
KERNEL_SIZE = 3
DOWNBOT = 20